MAIN_WINDOW_SIZE = 900, 600

CONTENT_LEFT_POLICY = 2, 1
CONTENT_MIDDLE_POLICY = 5, 1
CONTENT_RIGHT_POLICY = 3, 1

CONTENT_LEFT_TOOL_POLICY = 1, 0
CONTENT_LEFT_DIRTREE_POLICY = 1, 1

CONTENT_RIGHT_TOOL_POLICY = 1, 0
CONTENT_RIGHT_MIDDLE_POLICY = 1, 1

LEFT_MIN_TOOL_HEIGHT = 30
LEFT_MAX_TOOL_HEIGHT = 30
MIDDLE_MIN_TOOL_HEIGHT = LEFT_MIN_TOOL_HEIGHT
MIDDLE_MAX_TOOL_HEIGHT = LEFT_MAX_TOOL_HEIGHT
RIGHT_MIN_TOOL_HEIGHT = LEFT_MIN_TOOL_HEIGHT
RIGHT_MAX_TOOL_HEIGHT = LEFT_MAX_TOOL_HEIGHT
